### PR TITLE
Calculate fail in large image

### LINKED ISSUE #466: regression: missing per-frame histogram with 51200x51200 image
@zarda found this issue

with set_QA_performance/cube_A/cube_A_51200_z00001.fits, histogram is missing
Screen Shot 2020-03-11 at 9 37 02 PM

with set_QA_performance/cube_A/cube_A_38400_z00001.fits, it works fine
Screen Shot 2020-03-11 at 9 38 36 PM

potentially due to OpenMP replacement? @robsimmonds @veggiesaurus

### PR DESCRIPTION
**Pull request by zarda**
Fixed #466, use size_t instead of int to break the limitation of min/max and histogram calculator. (fixed)

### CODE REVIEW

File: Region/BasicStatsCalculator.h [hunk 1]
```diff
@@ -31,16 +31,16 @@ template <typename T>
 class BasicStatsCalculator {
     T _min_val, _max_val;
     double _sum, _sum_squares;
-    size_t _num_pixels;
```
Comment (veggiesaurus) [inline Region/BasicStatsCalculator.h]: Nothing wrong with using size_t, since it's just a #define for a 64bit int.

File: Region/Histogram.cc [hunk 2]
```diff
@@ -13,40 +13,47 @@ Histogram::Histogram(int num_bins, float min_value, float max_value, const std::
 
 Histogram::Histogram(Histogram& h, tbb::split) : _bin_width(h._bin_width), _min_val(h._min_val), _hist(h._hist.size(), 0), _data(h._data) {}
 
-void Histogram::operator()(const tbb::blocked_range<size_t>& r) {
-    std::vector<int> tmp(_hist);
+void Histogram::operator()(const tbb::blocked_range<uint64_t>& r) {
+    std::vector<uint64_t> tmp(_hist);
```
Comment (veggiesaurus) [inline Region/Histogram.cc]: Do we need to store the bins as 64bit? They get sent as 32bit ints anyway, don't they?

File: Region/Histogram.cc [hunk 3]
```diff
@@ -13,40 +13,47 @@ Histogram::Histogram(int num_bins, float min_value, float max_value, const std::
...
     for (auto i = r.begin(); i != r.end(); ++i) {
         auto v = _data[i];
         if (std::isnan(v) || std::isinf(v))
             continue;
-        int bin = std::max(std::min((int)((v - _min_val) / _bin_width), (int)_hist.size() - 1), 0);
+        // int bin = std::max(std::min((int)((v - _min_val) / _bin_width), (int)_hist.size() - 1), 0);
+        uint64_t _1 = (v - _min_val) / _bin_width;
+        uint64_t _2 = _hist.size() - 1;
+        uint64_t _3 = _1 < _2 ? _1 : _2;
+        uint64_t bin = _3 >= 0 ? _3 : 0;
```
Comment (veggiesaurus) [inline Region/Histogram.cc]: These changes aren't needed, are they? The new code is pretty ugly

**Review by veggiesaurus — CHANGES_REQUESTED** [review]
Using size_t is not s problem, so there are lots of needless changes here.

File: Region/BasicStatsCalculator.h (hunk 1 above)
Comment (zarda) [reply Region/BasicStatsCalculator.h]: got it. max size_t: 18446744073709551615

File: Region/Histogram.cc (hunk 3 above)
Comment (zarda) [reply Region/Histogram.cc]: Fixed

File: Region/Histogram.cc (hunk 2 above)
Comment (zarda) [reply Region/Histogram.cc]: Fixed

**Comment by kswang1029** [comment]
@zarda your new commit breaks the histogram
Screen Shot 2020-03-19 at 3 12 33 PM

**Comment by zarda** [comment]
Fixed the break of histogram. Thanks @kswang1029.

File: Region/Histogram.cc [hunk 4]
```diff
@@ -30,23 +31,23 @@ void Histogram::join(Histogram& h) { // NOLINT
...
-        for (auto i = start; i < end; i++) {
+    auto calc_lambda = [&](size_t start, size_t lstride) {
+        size_t* lbins = new size_t[_hist.size()];
+        size_t end = std::min((size_t)(start + lstride), _data.size());
+        memset(lbins, 0, _hist.size() * sizeof(size_t));
+        for (size_t i = start; i < end; i++) {
             auto v = _data[i];
             if (std::isfinite(v)) {
-                int binN = std::max(std::min((int)((v - _min_val) / _bin_width), (int)_hist.size() - 1), 0);
+                size_t binN = std::max<size_t>(std::min<size_t>((size_t)((v - _min_val) / _bin_width), (size_t)_hist.size() - 1), 0);
```
Comment (veggiesaurus) [inline Region/Histogram.cc]: this doesn't match our naming convention. Please use something like `bin_number`

Comment (veggiesaurus) [reply Region/Histogram.cc]: (I realise you weren't responsible for the actual name :smile: )

File: Region/Histogram.cc [hunk 5]
```diff
@@ -14,12 +14,13 @@ Histogram::Histogram(int num_bins, float min_value, float max_value, const std::
 Histogram::Histogram(Histogram& h, tbb::split) : _bin_width(h._bin_width), _min_val(h._min_val), _hist(h._hist.size(), 0), _data(h._data) {}
 
 void Histogram::operator()(const tbb::blocked_range<size_t>& r) {
-    std::vector<int> tmp(_hist);
+    std::vector<size_t> tmp(_hist);
```
Comment (veggiesaurus) [inline Region/Histogram.cc]: aren't we still using 64-bit bins here, though? The question is whether we definitely need them or not.

Comment (zarda) [reply Region/Histogram.cc]: The type size_t may reduce the performance. I suppose there might some extreme case while all bins are zero but one bin collects all counts. May I detect the size of incoming data to switch the type? I mean to assign type by template.

File: Region/Histogram.cc (hunk 4 above)
Comment (zarda) [reply Region/Histogram.cc]: Fixed

File: Region/Histogram.cc (hunk 5 above)
Comment (veggiesaurus) [reply Region/Histogram.cc]: I think trying to detect the size might make it slower (it will introduce a jump for each assigment. Given that we _already_ send the bins as `int32` in the protocol buffers, lets just stick to `int` here. If we find we need to adjust to 64-bit, we will need to do this for the protocol buffers as well (or switch to variable-length integers)

Comment (zarda) [reply Region/Histogram.cc]: Got it. Fixed them.

**Review by veggiesaurus — APPROVED** [review]
