### PR TITLE
Custom spdlog sink for logging to stdout/stderr from a single sink

### LINKED ISSUE #869: Log error and critical messages to stderr instead of stdout
Currently all messages logged to the console are written to `stdout`. It would be more consistent with *NIX conventions to use `stderr` correctly (and make it slightly easier to determine programmatically whether the backend has crashed, e.g. from the scripting wrapper). [This spdlog issue](https://github.com/gabime/spdlog/issues/345) discusses this exact use case and provides a suggested solution (a custom sink).

### PR DESCRIPTION
**Pull request by jolopezl**
Closes #869.

To get a _rerouting_ to stdout/stderr depending on the message level a custom sink for `spdlog` is introduced. While this is quite direct for a simple sink, it requires some code duplication if fancy colors are wanted, but I think it's ok.

To test it, I added within the main function the following messages after the logger initialization:
```
        spdlog::info("this should appear in stdout");
        spdlog::warn("this should appear in stdout");
        spdlog::error("this should appear in stderr");
        spdlog::critical("this should appear in stderr");
```
Then, I get:
```
$ ./carta_backend > logging.out 2> logging.err
^C$ cat logging.out 
[2022-01-17 15:37:38.224] [CARTA] [info] Writing to the log file: /Users/lopez/.carta/log/carta.log
[2022-01-17 15:37:38.224] [CARTA] [debug] Reading user settings from /Users/lopez/.carta/backend.json.
[2022-01-17 15:37:38.224] [CARTA] [info] this should appear in stdout
[2022-01-17 15:37:38.224] [CARTA] [warning] this should appear in stdout
[2022-01-17 15:37:38.227] [CARTA] [info] /Users/lopez/temp/CARTAvis/carta-backend/build/./carta_backend: Version 3.0.0-beta.2c
[2022-01-17 15:37:38.230] [CARTA] [info] CARTA gRPC service available at 0.0.0.0:50071
[2022-01-17 15:37:38.230] [CARTA] [info] CARTA gRPC token: EE7CC612-A49E-4278-A34E-AFB8B9AA472B
[2022-01-17 15:37:38.232] [CARTA] [info] Serving CARTA frontend from /Users/lopez/temp/CARTAvis/carta-frontend/build
[2022-01-17 15:37:38.232] [CARTA] [info] Listening on port 3020 with top level folder /, starting folder /Users/lopez/temp/CARTAvis/data, and 4 OpenMP worker threads
[2022-01-17 15:37:38.232] [CARTA] [info] CARTA is accessible at http://localhost:3020/?token=EDB898F1-FF87-44F3-A6EA-3E625E5E1D93
[2022-01-17 15:37:39.823] [CARTA] [info] Exiting backend.
$ cat logging.err 
[2022-01-17 15:37:38.224] [CARTA] [error] this should appear in stderr
[2022-01-17 15:37:38.227] [CARTA] [critical] this should appear in stderr
```

The only thing that puzzles me right now is that the `STDOUT_TAG`, now renames `CARTA_LOGGER_TAG` wasn't printed before. I am not sure if that was ok. Now you can see that the log messages come from `CARTA`. I think this is ok to notice the separation between CARTA and CASA logging messages clearly.

carta_backend_log

### CODE REVIEW

**Review by markccchiang — APPROVED** [review]

File: src/Logger/Logger.cc [hunk 1]
```diff
@@ -6,14 +6,19 @@
...
 
 void InitLogger(bool no_log_file, int verbosity, bool log_performance, bool log_protocol_messages_, fs::path user_directory) {
     log_protocol_messages = log_protocol_messages_;
 
-    // Set the stdout console
-    auto stdout_console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
-    stdout_console_sink->set_pattern(STDOUT_PATTERN);
+    // Set the stdout/stderr console
+    auto stdout_console_sink = std::make_shared<spdlog::sinks::carta_sink>();
+    stdout_console_sink->set_pattern(CARTA_LOGGER_PATTERN);
```
Comment (confluence) [inline src/Logger/Logger.cc]: This variable should probably be renamed to `console_sink`.

**Review by confluence — CHANGES_REQUESTED** [review]

**Review by confluence — APPROVED** [review]

**Review by veggiesaurus — APPROVED** [review]
