### PR TITLE
Fix the problem of loading JCMT-SCUBA2 FITS images

### LINKED ISSUE #1301: backend crashes when loading a JCMT-SCUBA2 FITS image
**Describe the bug**

A test JCMT-SCUBA2 image (from CADC) can be found here: https://drive.google.com/file/d/1ea8X58jHcgdNBBnNQm8OVk9E4rKqFXiP/view?usp=share_link

The macOS crash log:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000cf0
Exception Codes:       0x0000000000000001, 0x0000000000000cf0

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [55792]

VM Region Info: 0xcf0 is not in any region.  Bytes before following region: 68719473424
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)

> Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
> 0   carta_backend                 	       0x1028245ac carta::CartaFitsImage::internalDataType() const + 0
> 1   carta_backend                 	       0x102849414 carta::FitsLoader::OpenFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) + 1152
> 2   carta_backend                 	       0x1027b6ddc carta::FileExtInfoLoader::FillFileInfoFromImage(CARTA::FileInfoExtended&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&) + 72
> 3   carta_backend                 	       0x1027b6ba8 carta::FileExtInfoLoader::FillFileExtInfo(CARTA::FileInfoExtended&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&) + 444
> 4   carta_backend                 	       0x1027c4f58 carta::FileExtInfoLoader::FillFitsFileInfoMap(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, CARTA::FileInfoExtended, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, CARTA::FileInfoExtended>>>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&) + 512
> 5   carta_backend                 	       0x10299a624 carta::Session::FillExtendedFileInfo(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, CARTA::FileInfoExtended, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, CARTA::FileInfoExtended>>>&, CARTA::FileInfo&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&) + 336
> 6   carta_backend                 	       0x10299c670 carta::Session::OnFileInfoRequest(CARTA::FileInfoRequest const&, unsigned int) + 156
> 7   carta_backend                 	       0x1029acc74 carta::SessionManager::OnMessage(uWS::WebSocket<false, true, carta::PerSocketData>*, std::__1::basic_string_view<char, std::__1::char_traits<char>>, uWS::OpCode) + 1936
> 8   carta_backend                 	       0x1029b5610 uWS::WebSocketContext<false, true, carta::PerSocketData>::handleFragment(char*, unsigned long, unsigned int, int, bool, uWS::WebSocketState<true>*, void*) + 636
> 9   carta_backend                 	       0x1029b4878 bool uWS::WebSocketProtocol<true, uWS::WebSocketContext<false, true, carta::PerSocketData>>::consumeMessage<6u, unsigned char>(unsigned char, char*&, unsigned int&, uWS::WebSocketState<true>*, void*) + 812
> 10  carta_backend                 	       0x1029b4400 uWS::WebSocketProtocol<true, uWS::WebSocketContext<false, true, carta::PerSocketData>>::consume(char*, unsigned int, uWS::WebSocketState<true>*, void*) + 168
> 11  carta_backend                 	       0x1029b42f4 auto uWS::WebSocketContext<false, true, carta::PerSocketData>::init()::'lambda'(auto*, char*, int)::operator()<us_socket_t>(auto*, char*, int) const + 152
> 12  carta_backend                 	       0x102a5c034 us_loop_run + 208
> 13  carta_backend                 	       0x1029b1250 carta::SessionManager::RunApp() + 260
> 14  carta_backend                 	       0x10290dc40 main + 3500
> 15  dyld                          	       0x1a4e1ff28 start + 2236
> 

**To Reproduce**
1. download the test image
2. load it with the file browser, the backend will crash when we request file info.

**Expected behavior**
The image can be loaded successfully with CARTA

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Ventura
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 106
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

### PR DESCRIPTION
**Pull request by markccchiang**
**Description**

* What is implemented or fixed? Mention the linked issue(s), if any.
Closes #1301.

* How does this PR solve the issue? Give a brief summary.
The crash will happen if the BUNIT string from the header contains ` s**0.5`. To fix it, I just copied the function `ImageFITSConverter::getBrightnessUnit` from the casacore and modified it. Added a handler for such kind of BUNIT string. Not sure if there is another better way to solve this problem? 

* Are there any companion PRs (frontend, protobuf)?
No.

* Is there anything else that testers should know (e.g. exactly how to reproduce the issue)?
The crash will not happen when loading JCMT-SCUBA2 FITS images.

**Checklist**

- [x] changelog updated ~/ no changelog update needed~
- [x] e2e test passing / ~added corresponding fix~
- [x] ~protobuf updated to the latest dev commit /~ no protobuf update needed
- [ ] added reviewers and assignee
- [ ] added ZenHub estimate, milestone, and release

### CODE REVIEW

**Review by kswang1029 — APPROVED** [review]
tested and this should be fine. please proceed code review. 👍

File: src/ImageData/CartaFitsImage.cc [hunk 1]
```diff
@@ -318,7 +318,7 @@ void CartaFitsImage::SetUpImage() {
         setCoordinateInfo(coord_sys);
 
         // Set image units
-        setUnits(casacore::ImageFITSConverter::getBrightnessUnit(unused_headers, log));
+        setUnits(GetBrightnessUnit(unused_headers));
```
Comment (confluence) [inline src/ImageData/CartaFitsImage.cc]: Instead of copying this entire function from casacore, would it not be possible to preprocess `unused_headers` to replace this value in-place before calling the casacore function?

**Review by confluence — APPROVED** [review]
Great; this is a much simpler solution.

**Review by pford — APPROVED** [review]

**Comment by pford** [comment]
I am still puzzled why this image can be opened with casaviewer using casacore::FITSImage.

**Review by kswang1029 — APPROVED** [review]
tested. 👍
