### PR TITLE
Protect GILDAS unit from casacore Unit formatting

### LINKED ISSUE #1423: Header preview when opening FITS file displays * character as . character
**Describe the bug**
When opening a FITS file with file browser UI popup, the "File Information" and "Header" previews display the * character as a . character in the BUNIT keyword. E.g. if 'BUNIT = K (Ta*)' in the header, it shows up as 'BUNIT = K. (Ta.)' and 'Pixel unit = K. (Ta.)' in the frontend.

**To Reproduce**
1. Go to 'File' --> 'Open Image'
2. Click on any FITS file where the BUNIT keyword has a * character.
3. Scroll down to 'Pixel unit' in 'File Information' and 'BUNIT =' in 'Header'
4. See error.

**Expected behavior**
The frontend should display the * character properly. E.g. if 'BUNIT = K (Ta*)' in the header, it shows up as 'BUNIT = K (Ta*)' and 'Pixel unit = K (Ta*)' in the frontend.

**Screenshots or videos**
frontend_file_information
frontend_header
command_line_header

**Platform info (please complete the following information):**
 - OS: Linux RHEL
 - Browser: Mozilla Firefox
 - Browser version: 128.4.0esr (64-bit)
 - CARTA version: 4.1.0 (18 Jan 2024)

### PR DESCRIPTION
**Pull request by pford**
**Description**

* What is implemented or fixed? Mention the linked issue(s), if any.
Fixes #1423 
* How does this PR solve the issue? Give a brief summary.
Use regex to test for GILDAS unit, which includes a temperature type `<unit> (T<type>)`.  Prevent casacore::Unit from reformatting it in extended file info displayed in file browser and sent to frontend.  Also tests for casacore-ized version for unit stored in image, to avoid needlessly checking it.

* Are there any companion PRs (frontend, protobuf)?
No

* Is there anything else that testers should know (e.g. exactly how to reproduce the issue)?
Open image linked in issue, check that unit is displayed as "K (Ta*)".

**Checklist**

- [x] changelog updated / ~no changelog update needed~
- [x] e2e test passing / corresponding fix added / new e2e test created
- [ ] ICD test passing / corresponding fix added / new ICD test created
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] ~protobuf version bumped~ / protobuf version not bumped
- [x] added reviewers and assignee
- [ ] GitHub Project estimate added

### CODE REVIEW

**Comment by veggiesaurus** [comment]
Shouldn't we just ensure casacore doesn't change the unit at all? Not just this specific case.

**Comment by pford** [comment]
> Shouldn't we just ensure casacore doesn't change the unit at all? Not just this specific case.

I asked this question in the issue comments, @kswang1029 recommended that we do not change the current behavior.

File: src/Util/Casacore.cc [hunk 1]
```diff
@@ -257,6 +263,15 @@ void NormalizeUnit(casacore::String& unit) {
     }
 }
 
+bool IsGildasUnit(const casacore::String& unit) {
+    // Check if unit is in format from GILDAS CLASS software:
+    //     '<unit> (T<type>)' where the <type> describes the temperature T.
+    // Also test for casacore::Unit::check changes to the unit name where ' ' and '*' are replaced with '.'.
+    // For example: "K (Ta*)" -->  "K.(Ta.)" in casacore.
+    std::regex gildas_regex("[ ]*[a-zA-Z]+[ .]+\\(T[a-zA-Z_]+[*.]*\\)[ ]*");
+    return std::regex_match(unit, gildas_regex);
```
Comment (confluence) [inline src/Util/Casacore.cc]: 1. You can omit the `[]` around the space at the start and end.
2. I would define this regex as a const variable outside the function.

**Review by confluence — COMMENTED** [review]
I have minor suggestions for the regex, but apart from that this looks good.

**Comment by kswang1029** [comment]
> > Shouldn't we just ensure casacore doesn't change the unit at all? Not just this specific case.
> 
> I asked this question in the issue comments, @kswang1029 recommended that we do not change the current behavior.

I suggest we try the current solution for this issue in order to have minimal impact to the v5-stable release. The unit is the key for multiple spectral profile plot so it may introduce other issues if we adopt a global change at this stage. 

Having a global fix (eg preserve original unit string or something else) could happen in v6-beta.

**Review by kswang1029 — APPROVED** [review]
looks good.

File: src/Util/Casacore.cc (hunk 1 above)
Comment (pford) [reply src/Util/Casacore.cc]: Done, not sure why it is not showing this code as outdated.

File: src/Util/Casacore.cc [hunk 2]
```diff
@@ -257,6 +265,15 @@ void NormalizeUnit(casacore::String& unit) {
     }
 }
 
+bool IsGildasUnit(const casacore::String& unit) {
+    // Check if unit is in format from GILDAS CLASS software:
+    //     '<unit> (T<type>)' where the <type> describes the temperature T.
+    // Also test for casacore::Unit::check changes to the unit name where ' ' and '*' are replaced with '.'.
+    // For example: "K (Ta*)" -->  "K.(Ta.)" in casacore.
+    std::regex gildas_regex(GILDAS_UNIT_REGEX);
```
Comment (confluence) [inline src/Util/Casacore.cc]: Sorry, I meant defining the whole regex object outside, not just the string -- so that the object is created once, and not recreated whenever the function is called.

**Review by confluence — APPROVED** [review]
