### PR TITLE
careful handling of NaN values while contouring

### LINKED ISSUE #461: crazy contours when switching between no smooth and box smooth
Seen in the mac v1.3beta and dev on mix n match

To reproduce:
1) load an image
2) create contours with "no smooth" mode
3) switch to "box" smooth and regenerate contours 

M100_combine_CO_cube image mom0 pbcor-image-2020-3-6-14-48-18

test image attached
[M100_12m_CO_central.image.mom0.fits.zip](https://github.com/CARTAvis/carta-frontend/files/4296898/M100_12m_CO_central.image.mom0.fits.zip)

### PR DESCRIPTION
**Pull request by veggiesaurus**
Fixes #461 

Will  backport to `release/1.3` if its deemed to be a low-risk change by @pford or @confluence. @kswang1029 please double check that it's producing correct contours.

### CODE REVIEW

**Comment by kswang1029** [comment]
@veggiesaurus works! weird contours cannot be produced anymore.

File: Contouring.cc [hunk 1]
```diff
@@ -151,7 +160,12 @@ void TraceLevel(const float* image, int64_t width, int64_t height, double scale,
 
     // Search RightEdge
     for (j = 0; j < height - 1; j++) {
-        if (image[(j)*width + i] < level && level <= image[(j + 1) * width + i]) {
+        float pt_a = image[(j)*width + i];
+        float pt_b = image[(j + 1) * width + i];
+        pt_a = isnan(pt_a) ? -std::numeric_limits<float>::max() : pt_a;
```
Comment (pford) [inline Contouring.cc]: Why not just test for nan rather than reassign these values?
if (isnan(pt_a) || isnan(pt_b)) continue;
or
if (!isnan(pt_a) && !isnan(pt_b) && (pt_a > level && level >= pt_b)) {...}

**Comment by pford** [comment]
I see no reason why this can't go into 1.3.  Makes sense to ignore nans for contours.

**Review by confluence — APPROVED** [review]
This seems like a low-risk change for backporting into the release.

File: Contouring.cc (hunk 1 above)
Comment (veggiesaurus) [reply Contouring.cc]: simply skipping over `NaN` points will result in an infinite loop, because the `visited` array wouldn't get updated. 

However, you're right that I don't need to reassign these values. I've updated the code with the check 

`if ((isnan(pt_a) || pt_a < level) && level <= pt_b)`, since `level <= `NaN` will always be false, and if `pt_a` is a `NaN`, we still need to trace around it to update the `visited` array.

@confluence @pford please re-review, and @kswang1029 please confirm this still works after commit `26dbbf0`

**Review by confluence — APPROVED** [review]
Still seems OK.
