### PR TITLE
Recognize the FITS gzip file from ALMA archive

### LINKED ISSUE #1130: images as fits.gz from ALMA Science Archive not recognized by CARTA
**Describe the bug**
Reported by a v3 beta tester. Images as fits.gz downloaded from the ALMA Science Archive are not recognized by CARTA. If we unzip it and re-zip it (in my case with the gzip in macOS "Apple gzip 353.100.22"), the new fits.gz file can be recognized.

test images are attached
[test_by_mac_gzip.fits.gz](https://github.com/CARTAvis/carta-backend/files/8918988/test_by_mac_gzip.fits.gz)
[test_from_alma_archive.fits.gz](https://github.com/CARTAvis/carta-backend/files/8918993/test_from_alma_archive.fits.gz)

**To Reproduce**
1. download the example images above (or download such from the ALMA Science Archive directly)
2. check the file list and we will only see one image showing up

**Expected behavior**
The fits.gz images from the ALMA science archive should be recognized by CARTA.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Monterey
 - Browser [e.g. chrome, safari, electron app]: v3b3 electron app
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: v3b3 electron app
 - Frontend branch [e.g. dev, v3b2 release]: v3b3 electron app

### PR DESCRIPTION
**Pull request by markccchiang**
Closes #1130. It seems the magic number of fits.gz from ALMA archive is different from that of ordinary FITS gzip files. Although they are the same file type. @kswang1029 could you please check does it can also recognize the other fits.gz files from ALMA archive? Thank you!

### CODE REVIEW

**Comment by kswang1029** [comment]
uh, nice catch. Does this imply with different brands of gzip, the magic number is different?

**Comment by markccchiang** [comment]
> uh, nice catch. Does this imply with different brands of gzip, the magic number is different?

According to [this link](https://docs.fileformat.com/compression/gz/), the magic number of gz file is `1f 8b`. The other number corresponds to the compression method (usually `08` for DEFLATE) and file flags. The header of the ordinary gz file is `1f8b 0808` and the header of ALMA is `1f8b 0800`. I guess the only difference between them is the file flag. So maybe we can identify gz files by only checking whether it has `1f8b` number.

**Review by kswang1029 — APPROVED** [review]
checked with alma gz images and some others in the test image pool. All working. No regression is observed from e2e tests.

File: src/Util/File.cc [hunk 1]
```diff
@@ -34,6 +34,11 @@ bool IsCompressedFits(const std::string& filename) {
     return false;
 }
 
+bool IsGzFile(uint32_t magic_number) {
```
Comment (confluence) [inline src/Util/File.cc]: This is a confusing name for a function which takes a magic number as a parameter (not a file name or file object). I would suggest `IsGzMagicNumber` for more clarity.

**Review by confluence — CHANGES_REQUESTED** [review]
Other than the function name, I think this is fine.

**Review by confluence — APPROVED** [review]
