### PR TITLE
Angus/1213 no runtime config

### LINKED ISSUE #1213: Add the no-runtime-config flag back into dev and v3 branches
**Describe the bug**
NRAO archive needs to be able to serve CARTA from a backend build, but without the API/database stuff. The runtime config stuff is currently tied to whether the backend is opened with `--no_frontend`. 

I made a branch for v2.0 that solved this issue (`archived/angus/no_runtime_config`), but we would need to update this a bit for v3.0.

### PR DESCRIPTION
**Pull request by veggiesaurus**
**Description**

Closes #1213 by adding the `no_runtime_config` commandline argument. Workaround for the NRAO archive.

**Checklist**

- [x] changelog updated / ~~no changelog update needed~~
- [x] e2e test passing / ~~added corresponding fix~~
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed
- [x] added reviewers and assignee
- [x] added ZenHub estimate, milestone, and release

### CODE REVIEW

File: src/HttpServer/HttpServer.cc [hunk 1]
```diff
@@ -80,10 +82,14 @@ void HttpServer::RegisterRoutes() {
...
-    res->writeHeader("Content-Type", "application/json");
-    res->end(runtime_config.dump());
+    if (_enable_runtime_config) {
+        json runtime_config = {{"apiAddress", "/api"}};
+        res->writeStatus(HTTP_200);
+        res->writeHeader("Content-Type", "application/json");
+        res->end(runtime_config.dump());
+    } else {
+        res->writeStatus(HTTP_200)->end();
+    }
```
Comment (confluence) [inline src/HttpServer/HttpServer.cc]: I think this should be enabled or disabled in `RegisterRoutes`, not here, and return 501 (not implemented) for consistency with other disabled features (would that require a change in the calling code?).

If there's a good reason for it to return 200 anyway, I think we should still handle this logic in `RegisterRoutes` and make a different default handler (called something like `QuietSuccess`).

**Review by confluence — CHANGES_REQUESTED** [review]

File: src/HttpServer/HttpServer.cc (hunk 1 above)
Comment (veggiesaurus) [reply src/HttpServer/HttpServer.cc]: There's a good reason to return 200, because it just means there's no backend-mandated config. I can add it to a separate handler

**Review by confluence — APPROVED** [review]

**Comment by confluence** [comment]
This has been tested by @kswang1029, and the flag does cause saved preferences to be ignored.
