### PR TITLE
Handle invalid database objects correctly

### LINKED ISSUE #1485: setting preference will reset preferences.json
**Describe the bug**
This is a case to reproduce the issue. Not sure if there are others.

If we set WCS format to degrees, the preferences.json will be set to default so that the original custom preferences will be gone.

Image

**To Reproduce**
1. Go to Preferences, Render configuration, set colormap to jet
2. load an image to see it does what it supposed to do 
3. Check preferences.json to see the colormap setup
4. Go to Preferences, WCS and Image Overlay, and set WCS format as degree.
5. load an image to see it does what it supposed to do 
6. but now preferences.json has been reset so we do not see the colormap preference.
7. close CARTA and launch CARTA again
8. see prompt for telemetry. This is also an indication that the preferences.json has been reset.
 
 
**Expected behavior**
Being able to write preferences without altering existing ones.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: Sequoia 
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 
 - Backend branch [e.g. dev, v3b2 release]: dev, v5
 - Frontend branch [e.g. dev, v3b2 release]: dev, v5

### PR DESCRIPTION
**Pull request by confluence**
**Description**

Fixes #1485.

The functions which save database objects to disk open the file for writing before performing validation. This means that if validation fails, the file is left blank. This PR moves the opening of the file to just before it is needed for writing, after the validation step. The invalid update is just ignored (which is what currently happens in the controller).

The actual invalid preferences which triggered this issue need separate fixes in these companion PRs:

1. In the [schema definition](https://github.com/CARTAvis/schemas/pull/10) (which is incorrect)
2. In the [frontend](https://github.com/CARTAvis/carta-frontend/pull/2563) (which needs a shim in the upgrade function to correct existing preferences which previous versions of the backend would have allowed to be saved).
3. In the [controller](https://github.com/CARTAvis/carta-controller/pull/239) (which needs the schema update)

This also needs to be merged into the 5.0 branch.

Still to be done:

- [X] The validator library documentation suggests that the default exception thrown by the validator includes a detailed description of the validation error(s), but it's actually just reported as a generic exception. This can be fixed with a custom validator (we already have one that we can reuse with a custom exception).
- [ ] ~The controller sends data in failure responses which contains the error status and a specific error message. The backend does not do this. For parity with the controller, it should send back the same data with the same message under the same circumstances.~ This is not critical, and I would like to adjust the controller's messages. I will make separate issues for this.
- [X] This PR should also include the schemas fix.
- [X] Updated prefs should be validated *before*, not *after* merge with existing prefs before write to file. Otherwise an existing invalid preference will block writes forever.
- [X] Assorted other small issues found and fixed.

**Checklist**

- [X] changelog updated
- [ ] e2e test passing / corresponding fix added / new e2e test created
- [ ] ICD test passing / corresponding fix added / new ICD test created
- [X] no protobuf update needed
- [X] protobuf version not bumped
- [X] added reviewers and assignee
- [ ] GitHub Project estimate added

### CODE REVIEW

**Review by loveluthien — APPROVED** [review]
Looks good. 😎

**Review by veggiesaurus — APPROVED** [review]

**Comment by kswang1029** [comment]
@confluence if I manually add 
`"colormap": x`
in the preferences.json

once I launch carta I will be asked for telemetry permission and it seems my preferences.json is being reset. Could you confirm?

In addition, if we add an undefined key:value pair like
`"sponge":"bob",`
it will stay forever in the json file. Should we remove it plus a warning to user? @loveluthien

**Comment by loveluthien** [comment]
Follow the previous comment, any key with a value that is not a number or a string will cause the preferences.json file to be reset.

**Comment by confluence** [comment]
> @confluence if I manually add `"colormap": x` in the preferences.json
> 
> once I launch carta I will be asked for telemetry permission and it seems my preferences.json is being reset. Could you confirm?

I will check -- I may have missed incorrect handling of malformed JSON.

> In addition, if we add an undefined key:value pair like `"sponge":"bob",` it will stay forever in the json file. Should we remove it plus a warning to user? @loveluthien

We don't currently do anything about unrecognised properties -- all the schemas allow extra properties. It's up to you whether the frontend should handle them -- I agree that it may be helpful if the user makes a key typo, but perhaps this should wait for future refactoring.

File: src/HttpServer/HttpServer.cc [hunk 1]
```diff
@@ -255,6 +255,19 @@ bool HttpServer::ValidateObject(const std::string& object_type, nlohmann::json&
...
+    auto preferences_path = _config_folder / "preferences.json";
+    auto backup_path = _config_folder / "preferences.json.bak";
+    std::error_code error_code;
+
+    fs::copy_file(preferences_path, backup_path, fs::copy_options::update_existing, error_code);
+    if (error_code) {
+        spdlog::warn("Could not back up preferences: {}", error_code.message());
+    } else {
+        spdlog::info("Backed up preferences to {}.", backup_path.string());
+    }
```
Comment (kswang1029) [inline src/HttpServer/HttpServer.cc:268]: would be good to add another log like

"Resetting factory defaults."

**Review by kswang1029 — APPROVED** [review]
this looks good after a final tweak in the log message when a malformed preference is detected.

File: src/HttpServer/HttpServer.cc (hunk 1 above)
Comment (confluence) [reply src/HttpServer/HttpServer.cc:268]: I will add an explanatory message to the handler for setting preferences (which is where this is triggered -- the existing preferences will only be reset when the frontend tries to update them).
