### PR TITLE
Yuhsuan/1318 fix fitting mad

### LINKED ISSUE #1318: Image fitting: MAD calculation of images with nans
**Describe the bug**
(Found by @acdo2002) The MAD (median absolute deviation) calculation becomes lower when more additional nans are included in the fitting data. When std is 0 (with a large number of nans), the fitting fails.

**Screenshots or videos**
image

**To Reproduce**
1. Fit the entire image and the fitting fails.

**Expected behavior**
The MAD calculation does not change when additional nans are included (and the fitting result does not change).
Fitting the entire image does not fail.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Big Sur
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 117
 - Backend branch [e.g. dev, v3b2 release]: dev, v4
 - Frontend branch [e.g. dev, v3b2 release]: dev, v4

**Additional context**
[Download test image](https://drive.google.com/file/d/1WhyovU0w1mwiP1FoLiZb9SEK5Ro0S6iE/view?usp=sharing)

### PR DESCRIPTION
**Pull request by YuHsuan-Hwang**
**Description**

* What is implemented or fixed? Mention the linked issue(s), if any.
  Fixed #1318.
* How does this PR solve the issue? Give a brief summary.
  Exclude nans when calculating MAD (median absolute deviation). Instead of using the raw image data, create a tmp double array with image data excluding nans for the calculation.
* Other changes:
  Minor adjustment of the unit test - extend the area of FOV fitting to get a more precise result.
* Tested that:
  The fitting result and MAD does not change when additional nans are included.
  Fitting the entire test image does not get MAD 0 and does not fail.
  Also checked that the calculation time and the memory pattern do not change.

**Checklist**

- [x] changelog updated / ~no changelog update needed~
- [x] e2e test passing / corresponding fix added / ~new e2e test created~
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] added reviewers and assignee
- [x] added ZenHub estimate, milestone, and release

### CODE REVIEW

**Review by pford — APPROVED** [review]

**Review by markccchiang — APPROVED** [review]

**Review by acdo2002 — APPROVED** [review]

**Comment by kswang1029** [comment]
@YuHsuan-Hwang if the input image does not have any NaN pixels, do we expect to see slightly different fitting results in this PR comparing to dev?

I see the solution is to have a double array to exclude NaN. Would it be sensible to refer to BITPIX for the array declaration? Not sure this is the root cause for the above question?

File: src/ImageFitter/ImageFitter.cc [hunk 1]
```diff
@@ -141,13 +141,19 @@ void ImageFitter::StopFitting() {
     _fit_data.stop_fitting = true;
 }
 
-void ImageFitter::CalculateNanNum() {
+void ImageFitter::CalculateNanNumAndStd() {
+    std::vector<double> data_notnan;
```
Comment (confluence) [inline src/ImageFitter/ImageFitter.cc:145]: I would suggest calling `reserve` on this vector (with the original data size, which is the upper limit) to avoid possible reallocations as it is filled up.

(What is the size of the data that we're duplicating here -- one full image channel? Is there a significant memory usage impact when the image is large?)

**Review by confluence — APPROVED** [review]

**Comment by YuHsuan-Hwang** [comment]
@kswang1029 
> if the input image does not have any NaN pixels, do we expect to see slightly different fitting results in this PR comparing to dev?

Yes, there are slightly changes because my previous workaround triggers some preprocessing to the array.

> I see the solution is to have a double array to exclude NaN. Would it be sensible to refer to BITPIX for the array declaration? Not sure this is the root cause for the above question?

Double array is required for the GSL function.

File: src/ImageFitter/ImageFitter.cc (hunk 1 above)
Comment (YuHsuan-Hwang) [reply src/ImageFitter/ImageFitter.cc:145]: Thanks for the comment. `reserve` is added.

The size of the data is an image channel. Yes, it can be large with large images, but it should be temporary and the workspace `gsl_multifit_nlinear_workspace` used in the fitting process is larger than it.

**Comment by YuHsuan-Hwang** [comment]
Debug log "MAD = ..." is added so that testing is easier.

**Review by loveluthien — APPROVED** [review]
It works well.

**Review by kswang1029 — APPROVED** [review]
looks fine. corresponding e2e tests are updated. no other regression seen from e2e tests.
