### PR TITLE
Fix crash in channel map ICD test with ASAN enabled

### LINKED ISSUE #1518: Backend crash with ICD channel map test when built with AddressSanitizer
The newly added ICD channel map test triggers a backend crash if the backend is compiled with `AddressSanitizer` enabled. The problem does not occur when AddressSanitizer is disabled.

Steps to reproduce:

1. Clone and build the ICD test repository branch:

```
git clone -b mark/test_channel_map https://github.com/CARTAvis/ICD-RxJS.git
cd ICD-RxJS

git submodule update --init --recursive    
npm install
cd protobuf
./build_proto.sh
``` 

2. Build the backend with AddressSanitizer enabled, for example:

```
cmake $SRC_DIR \
            -Dtest=on \
            -DCMAKE_BUILD_TYPE=Debug \
            -DDevSuppressExternalWarnings=ON \
            -DCMAKE_CXX_FLAGS="-O0 -g -fsanitize=address -fno-omit-frame-pointer" \
            -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address"
```

3. Run the backend with:

```
ASAN_OPTIONS=suppressions=../debug/asan/myasan.supp \
LSAN_OPTIONS=suppressions=../debug/asan/myasan-leaks.supp \
ASAN_SYMBOLIZER_PATH=llvm-symbolizer \
./carta_backend /images --top_level_folder /images \
    --port 3002 \
    --omp_threads=4 --debug_no_auth --no_frontend --no_database --verbosity=5
```

4. Run the ICD channel map test (under the directory `ICD-RxJS`):

```
npm test src/test/CHANNEL_MAP.test.ts
```

The corresponding error log is attached below:

<details>
<summary>View error log</summary>
[2025-08-26 06:24:33.982Z] [CARTA] [debug] Set channel map current range 0-3 channel range 1-3
[2025-08-26 06:24:33.982Z] [CARTA] [debug] Send channel 1 in range 1-3
=================================================================
==20587==ERROR: AddressSanitizer: heap-use-after-free on address 0x00010bf9cc00 at pc 0x000102606ccc bp 0x00016dbd2f90 sp 0x00016dbd2f88
READ of size 4 at 0x00010bf9cc00 thread T2
==20587==WARNING: invalid path to external symbolizer!
==20587==WARNING: Failed to use and restart external symbolizer!
    #0 0x102606cc8 in carta::NearestNeighbor(float const*, float*, long long, long long, long long, long long, long long, int) (.omp_outlined_debug__)+0x85c (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1002cacc8)
    #1 0x102606fc4 in carta::NearestNeighbor(float const*, float*, long long, long long, long long, long long, long long, int) (.omp_outlined)+0x70 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1002cafc4)
    #2 0x106829d28 in __kmp_invoke_microtask+0x98 (/opt/homebrew/Cellar/libomp/20.1.1/lib/libomp.dylib:arm64+0x6dd28)
    #3 0x16dbd38bc  (<unknown module>)

0x00010bf9cc00 is located 656384 bytes inside of 2048000-byte region [0x00010befc800,0x00010c0f0800)
freed by thread T2 here:
    #0 0x1092482d4 in _ZdlPv+0x74 (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/lib/darwin/libclang_rt.asan_osx_dynamic.dylib:arm64e+0x642d4)
    #1 0x1023ed374 in void std::__1::__libcpp_operator_delete[abi:ne180100]<void*>(void*)+0x14 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1000b1374)
    #2 0x1023ed324 in void std::__1::__do_deallocate_handle_size[abi:ne180100]<>(void*, unsigned long)+0x18 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1000b1324)
    #3 0x1023ed2c8 in std::__1::__libcpp_deallocate[abi:ne180100](void*, unsigned long, unsigned long)+0x4c (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1000b12c8)
    #4 0x1024c82b4 in std::__1::allocator<float>::deallocate[abi:ne180100](float*, unsigned long)+0x28 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x10018c2b4)
    #5 0x1024c7e90 in std::__1::allocator_traits<std::__1::allocator<float>>::deallocate[abi:ne180100](std::__1::allocator<float>&, float*, unsigned long)+0x24 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x10018be90)
    #6 0x1024c7cf8 in std::__1::vector<float, std::__1::allocator<float>>::__destroy_vector::operator()[abi:ne180100]()+0x214 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x10018bcf8)
    #7 0x1024c79c0 in std::__1::vector<float, std::__1::allocator<float>>::~vector[abi:ne180100]()+0x140 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x10018b9c0)
    #8 0x1024c062c in std::__1::vector<float, std::__1::allocator<float>>::~vector[abi:ne180100]()+0x18 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x10018462c)
    #9 0x10270726c in carta::Frame::GetRasterData(int, std::__1::vector<float, std::__1::allocator<float>>&, CARTA::ImageBounds&, int, bool)+0xbc8 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1003cb26c)
    #10 0x10270d164 in carta::Frame::GetRasterTileData(int, std::__1::shared_ptr<std::__1::vector<float, std::__1::allocator<float>>>&, carta::Tile const&, int&, int&)+0x15cc (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1003d1164)
    #11 0x10270a6e8 in carta::Frame::FillRasterTileData(CARTA::RasterTileData&, carta::Tile const&, int, int, CARTA::CompressionType, float, bool)+0x5ac (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1003ce6e8)
    #12 0x10347bebc in carta::Session::OnAddRequiredTiles(CARTA::AddRequiredTiles const&, int, int, bool) (.omp_outlined_debug__)+0xee0 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x10113febc)
    #13 0x10347c728 in carta::Session::OnAddRequiredTiles(CARTA::AddRequiredTiles const&, int, int, bool) (.omp_outlined)+0xa0 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x101140728)
    #14 0x106829d28 in __kmp_invoke_microtask+0x98 (/opt/homebrew/Cellar/libomp/20.1.1/lib/libomp.dylib:arm64+0x6dd28)

previously allocated by thread T2 here:
    #0 0x109247e94 in _Znwm+0x74 (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/lib/darwin/libclang_rt.asan_osx_dynamic.dylib:arm64e+0x63e94)
    #1 0x1023eb578 in void* std::__1::__libcpp_operator_new[abi:ne180100]<unsigned long>(unsigned long)+0x14 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1000af578)
    #2 0x1023eb4dc in std::__1::__libcpp_allocate[abi:ne180100](unsigned long, unsigned long)+0x44 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1000af4dc)
    #3 0x1024e6104 in std::__1::allocator<float>::allocate[abi:ne180100](unsigned long)+0x4c (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1001aa104)
    #4 0x1024e5e50 in std::__1::__allocation_result<std::__1::allocator_traits<std::__1::allocator<float>>::pointer> std::__1::__allocate_at_least[abi:ne180100]<std::__1::allocator<float>>(std::__1::allocator<float>&, unsigned long)+0x124 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1001a9e50)
    #5 0x1024e59f0 in std::__1::__split_buffer<float, std::__1::allocator<float>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<float>&)+0x210 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1001a99f0)
    #6 0x1024e4364 in std::__1::__split_buffer<float, std::__1::allocator<float>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<float>&)+0x30 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1001a8364)
    #7 0x1024e3990 in std::__1::vector<float, std::__1::allocator<float>>::__append(unsigned long)+0x268 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1001a7990)
    #8 0x1024d6160 in std::__1::vector<float, std::__1::allocator<float>>::resize(unsigned long)+0x5c (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x10019a160)
    #9 0x10270648c in carta::Frame::GetZMatrix(std::__1::vector<float, std::__1::allocator<float>>&, unsigned long, unsigned long)+0x21c (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1003ca48c)
    #10 0x102707250 in carta::Frame::GetRasterData(int, std::__1::vector<float, std::__1::allocator<float>>&, CARTA::ImageBounds&, int, bool)+0xbac (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1003cb250)
    #11 0x10270d164 in carta::Frame::GetRasterTileData(int, std::__1::shared_ptr<std::__1::vector<float, std::__1::allocator<float>>>&, carta::Tile const&, int&, int&)+0x15cc (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1003d1164)
    #12 0x10270a6e8 in carta::Frame::FillRasterTileData(CARTA::RasterTileData&, carta::Tile const&, int, int, CARTA::CompressionType, float, bool)+0x5ac (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1003ce6e8)
    #13 0x10347bebc in carta::Session::OnAddRequiredTiles(CARTA::AddRequiredTiles const&, int, int, bool) (.omp_outlined_debug__)+0xee0 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x10113febc)
    #14 0x10347c728 in carta::Session::OnAddRequiredTiles(CARTA::AddRequiredTiles const&, int, int, bool) (.omp_outlined)+0xa0 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x101140728)
    #15 0x106829d28 in __kmp_invoke_microtask+0x98 (/opt/homebrew/Cellar/libomp/20.1.1/lib/libomp.dylib:arm64+0x6dd28)

Thread T2 created by T0 here:
    #0 0x1092301c8 in pthread_create+0x5c (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/lib/darwin/libclang_rt.asan_osx_dynamic.dylib:arm64e+0x4c1c8)
    #1 0x1030885c8 in std::__1::__libcpp_thread_create[abi:ne180100](_opaque_pthread_t**, void* (*)(void*), void*)+0x28 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x100d4c5c8)
    #2 0x1038110c4 in std::__1::thread::thread<carta::ThreadManager::StartEventHandlingThreads(int)::$_0&, void>(carta::ThreadManager::StartEventHandlingThreads(int)::$_0&)+0x1d4 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1014d50c4)
    #3 0x103810168 in std::__1::thread::thread<carta::ThreadManager::StartEventHandlingThreads(int)::$_0&, void>(carta::ThreadManager::StartEventHandlingThreads(int)::$_0&)+0x20 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1014d4168)
    #4 0x10380feac in carta::ThreadManager::StartEventHandlingThreads(int)+0x198 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1014d3eac)
    #5 0x1030928f8 in main+0x12c8 (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x100d568f8)
    #6 0x18b140270  (<unknown module>)

SUMMARY: AddressSanitizer: heap-use-after-free (/Users/acdc/mark/carta-backend/build/carta_backend:arm64+0x1002cacc8) in carta::NearestNeighbor(float const*, float*, long long, long long, long long, long long, long long, int) (.omp_outlined_debug__)+0x85c
Shadow bytes around the buggy address:
  0x00010bf9c980: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x00010bf9ca00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x00010bf9ca80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x00010bf9cb00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x00010bf9cb80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x00010bf9cc00:[fd]fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x00010bf9cc80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x00010bf9cd00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x00010bf9cd80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x00010bf9ce00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x00010bf9ce80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==20587==ABORTING
</details>

The test succeeds if the backend is built *without* AddressSanitizer.

### PR DESCRIPTION
**Pull request by confluence**
**Description**

Fixes #1518. In `Frame::GetRasterData` a vector was being declared inside a conditional block, which was causing the vector to go out of scope while its data (accessed through a separate pointer) was still being used.

Please see the issue for detailed steps to reproduce. I ran the single ICD test locally to test the fix.

**Checklist**

- [X] changelog updated
- [ ] e2e test passing / corresponding fix added / new e2e test created
- [ ] ICD test passing / corresponding fix added / new ICD test created
- [X] no protobuf update needed
- [X] protobuf version not bumped
- [X] added reviewers and assignee
- [ ] GitHub Project estimate added

### CODE REVIEW

File: src/Frame/Frame.cc [hunk 1]
```diff
@@ -453,12 +453,12 @@ bool Frame::GetRasterData(int z, std::vector<float>& image_data, CARTA::ImageBou
 
     Timer t;
     float* z_data;
+    std::vector<float> z_matrix;
```
Comment (veggiesaurus) [inline src/Frame/Frame.cc]: I think `z_matrix` made sense as a name when it was just scoped to that branch, but here it's a bit confusing. Perhaps `uncached_matrix_buffer` or something like that would make more sense?

Comment (confluence) [reply src/Frame/Frame.cc]: Good idea. I think we should also rename the `GetZMatrix` function, but I didn't want to do that in this PR.

**Review by markccchiang — APPROVED** [review]
Confirm that the newly modified code passes the channel map test.

File: src/Frame/Frame.cc (hunk 1 above)
Comment (confluence) [reply src/Frame/Frame.cc]: I renamed the function in this branch (it's a relatively contained change).

This is a bit messy: `GetZSlice` calls `GetSlicerData`, which has its own logic for using the cache if possible. However, it copies the data, which is unnecessary here. This will all change when the cache is refactored; for now I have left everything else as it is.

**Review by kswang1029 — APPROVED** [review]
e2e tests are passing.

**Review by pford — APPROVED** [review]

**Review by veggiesaurus — APPROVED** [review]
