### PR TITLE
Logging ICD messages

### LINKED ISSUE #475: [question] logging ICD message history in verbose mode
Currently when verbose mode is enabled, the log seems not providing sufficient information when the backend crashed (well, it is seg fault but it is not trivial to see which step caused the crash). I am wondering if it is possible to log all ICD messages in the log as well? @veggiesaurus @pford @ajm-asiaa

### PR DESCRIPTION
**Pull request by markccchiang**
Closes #475. Logging ICD messages when setting `--verbosity 6` (trace mode).

### CODE REVIEW

**Review by veggiesaurus — CHANGES_REQUESTED** [review]
I think we need a separate log level for this. Performance logging shouldn't be conflated with ICD logging. Rather introduce a separate level (7?) And use that

File: src/SessionManager/ProgramSettings.cc [hunk 1]
```diff
@@ -76,7 +76,8 @@ ProgramSettings::ProgramSettings(int argc, char** argv) {
  3   warning
  4   info
  5   debug
- 6   trace)");
+ 6   trace
```
Comment (confluence) [inline src/SessionManager/ProgramSettings.cc]: Should we rename this to `performance` (just here, in the user-facing information)?

It's also apparently possible to create a custom log formatter to change the level name(s) in the logs, but I'm not sure if that's absolutely necessary.

Maybe `trace (performance)`?

File: src/SessionManager/ProgramSettings.cc [hunk 2]
```diff
@@ -76,7 +76,8 @@ ProgramSettings::ProgramSettings(int argc, char** argv) {
...
+ 7   trace + ICD)");
```
Comment (confluence) [inline src/SessionManager/ProgramSettings.cc]: Similarly, I think that we should rename this to something like `protocol` or `trace (protocol)`.

It's already implied that each level includes the levels above it.

(ICD is our internal term for a document.)

File: src/Logger/Logger.cc [hunk 3]
```diff
@@ -111,17 +117,21 @@ std::unordered_map<CET, std::string> event_type_map = {{CET::EMPTY_EVENT, "EMPTY
...
 void LogReceivedEventType(const CARTA::EventType& event_type) {
-    if (event_type_map.count(event_type)) {
-        spdlog::trace("[<==] {}", event_type_map[event_type]);
-    } else {
-        spdlog::error("Unknown event type: {}!", event_type);
+    if (log_icd_messages) {
+        if (event_type_map.count(event_type)) {
+            spdlog::trace("[<==] {}", event_type_map[event_type]);
+        } else {
+            spdlog::error("Unknown event type: {}!", event_type);
```
Comment (confluence) [inline src/Logger/Logger.cc]: I think we should always log these errors, and only log the non-error messages if `log_icd_messages` is set.

File: src/Logger/Logger.cc [hunk 4]
```diff
@@ -111,17 +117,21 @@ std::unordered_map<CET, std::string> event_type_map = {{CET::EMPTY_EVENT, "EMPTY
...
 void LogSentEventType(const CARTA::EventType& event_type) {
-    if (event_type_map.count(event_type)) {
-        spdlog::trace("[==>] {}", event_type_map[event_type]);
-    } else {
-        spdlog::error("Unknown event type: {}!", event_type);
+    if (log_icd_messages) {
+        if (event_type_map.count(event_type)) {
+            spdlog::trace("[==>] {}", event_type_map[event_type]);
+        } else {
+            spdlog::error("Unknown event type: {}!", event_type);
```
Comment (confluence) [inline src/Logger/Logger.cc]: As above.

**Review by confluence — CHANGES_REQUESTED** [review]
I think we should change the level names in the help, and always log errors caused by unrecognised messages.

I was hoping that we could define custom levels in spdlog, but it doesn't look like it's possible, and there's a closed issue which suggests that it will never be implemented. So I think this custom handling is OK.

File: src/SessionManager/ProgramSettings.cc (hunk 2 above)
Comment (veggiesaurus) [inline src/SessionManager/ProgramSettings.cc]: each level implies all the previous levels. I suggest you just say "ICD". I also think we should rename "trace" to `performance`. We can use `#defines` to customise the `spdlog::trace` prefix as well

Comment (veggiesaurus) [reply src/SessionManager/ProgramSettings.cc]: the one problem with that is that we're still calling `spdlog::trace` when logging performance. We can add a function alias though:
```
// Adds an alias to trace for consistency between function name and prefix
namespace spdlog {
constexpr auto performance = [](auto&& ...args) {
    return trace(std::forward<decltype(args)>(args)...);
};
```

File: src/SessionManager/ProgramSettings.cc (hunk 1 above)
Comment (veggiesaurus) [reply src/SessionManager/ProgramSettings.cc]: Agreed. See below for example of how to move from "trace" to "performance"

File: src/SessionManager/ProgramSettings.cc (hunk 2 above)
Comment (veggiesaurus) [reply src/SessionManager/ProgramSettings.cc]: I agree, protocol makes more sense than ICD

Comment (markccchiang) [reply src/SessionManager/ProgramSettings.cc]: So should we rename all the `spdlog::trace` as `spdlog::performance` in the original code. And add a new customize `spdlog::icd` as well?

Comment (veggiesaurus) [reply src/SessionManager/ProgramSettings.cc]: I think we should rename the existing `spdlog::trace`, yes. Not sure about adding a new ICD, since we only use it once.

Comment (confluence) [reply src/SessionManager/ProgramSettings.cc]: This alias isn't reflected in the logged level names, right?

Comment (markccchiang) [reply src/SessionManager/ProgramSettings.cc]: Another way is that we can create a new logger and customize its format. I guess.

Comment (veggiesaurus) [reply src/SessionManager/ProgramSettings.cc]: we need to do that too. Something like 
```#define SPDLOG_LEVEL_NAMES {"performance", "debug", "info", "warning", "error", "critical", "off" }```

_before_ including `spdlog.h` would do it

File: src/SessionManager/ProgramSettings.cc [hunk 5]
```diff
@@ -76,7 +76,8 @@ ProgramSettings::ProgramSettings(int argc, char** argv) {
  3   warning
  4   info
  5   debug
- 6   trace)");
+ 6   performance
+ 7   ICD)");
```
Comment (confluence) [inline src/SessionManager/ProgramSettings.cc]: Please change this to `protocol`.

**Review by veggiesaurus — APPROVED** [review]
I'm happy with these changes. @kswang1029 please test the output to see if we can merge and close #475

**Comment by kswang1029** [comment]
@veggiesaurus will do

**Comment by kswang1029** [comment]
> [2021-02-25 11:04:16.385] [performance] [==>] SPATIAL_PROFILE_DATA
[2021-02-25 11:04:16.468] [performance] [<==] SET_CURSOR
[2021-02-25 11:04:16.468] [performance] Fill spatial profile in 0.014 ms
[2021-02-25 11:04:16.468] [performance] [==>] SPATIAL_PROFILE_DATA
[2021-02-25 11:04:16.669] [performance] [<==] SET_CURSOR
[2021-02-25 11:04:16.669] [performance] Fill spatial profile in 0.013000000000000001 ms
[2021-02-25 11:04:16.669] [performance] [==>] SPATIAL_PROFILE_DATA
[2021-02-25 11:04:17.491] [performance] [<==] SET_SPECTRAL_REQUIREMENTS
[2021-02-25 11:04:17.612] [performance] [==>] SPECTRAL_PROFILE_DATA
[2021-02-25 11:04:17.612] [performance] Fill spectral profile in 120.863 ms
[2021-02-25 11:04:25.222] [info] Client 1 [127.0.0.1] Deleted. Remaining sessions: 1
[2021-02-25 11:04:25.222] [debug] 0x7fb2fe809a00 ~Session 0
[2021-02-25 11:04:25.222] [info] No remaining sessions.
[2021-02-25 11:04:26.575] [debug] 0x7fb2fd83ac00 ::Session (1)
[2021-02-25 11:04:26.575] [info] Session 2 [127.0.0.1] Connected. Num sessions: 1
[2021-02-25 11:04:26.647] [performance] [<==] REGISTER_VIEWER
[2021-02-25 11:04:26.647] [performance] [==>] REGISTER_VIEWER_ACK

I see with verbosity=7 protocol messages and performance info are all with [performance]. Is this expected? For protocol messages, shouldn't it be [protocol] (much easier for log post-processing when needed)?

**Comment by veggiesaurus** [comment]
> I see with verbosity=7 protocol messages and performance info are all with [performance]. Is this expected? For protocol messages, shouldn't it be [protocol] (much easier for log post-processing when needed)?

I think this is one of the issues with spdlog, and adding another level would complicate matters quite a bit. I suggest we replace it with `[info]`, since its less misleading than `[performance]`. And then in terms of post-processing, you can just grep for `==>` or `<==`

@markccchiang I think you can use `spdlog::info` for the ICD messages, it's also already behind your `log_icd_messages` flag

**Comment by confluence** [comment]
If we're going to do that, I'd really prefer to use `debug` -- I think that's much more suitable; this is far too verbose for `info`.

**Comment by veggiesaurus** [comment]
> If we're going to do that, I'd really prefer to use `debug` -- I think that's much more suitable; this is far too verbose for `info`.

good point

**Review by veggiesaurus — APPROVED** [review]

**Comment by veggiesaurus** [comment]
@kswang1029 are you happy with `[2021-02-25 11:04:26.647] [debug] [<==] REGISTER_VIEWER`

**Comment by kswang1029** [comment]
Yes using debug is sensible 👍

File: src/Logger/Logger.cc [hunk 6]
```diff
@@ -55,6 +57,10 @@ void InitLogger(bool no_log_file, int verbosity) {
         case 6:
             stdout_logger->set_level(spdlog::level::trace);
             break;
+        case 7:
+            stdout_logger->set_level(spdlog::level::trace);
```
Comment (confluence) [inline src/Logger/Logger.cc]: This should be `debug` now, and we should switch 6 and 7 around.

File: src/SessionManager/ProgramSettings.cc [hunk 7]
```diff
@@ -76,7 +76,8 @@ ProgramSettings::ProgramSettings(int argc, char** argv) {
  3   warning
  4   info
  5   debug
- 6   trace)");
+ 6   performance
+ 7   protocol)");
```
Comment (confluence) [inline src/SessionManager/ProgramSettings.cc]: Swap 6 and 7, and I suggest changing "protocol" to something like "+ protocol messages", otherwise users will expect a level called protocol in the logs, which we don't have.

**Review by confluence — CHANGES_REQUESTED** [review]

File: src/Logger/Logger.cc (hunk 6 above)
Comment (veggiesaurus) [reply src/Logger/Logger.cc]: I don't know about that actually. The ICD logging is the most verbose logging we'd want, so it should still be 7.

File: src/SessionManager/ProgramSettings.cc (hunk 7 above)
Comment (veggiesaurus) [reply src/SessionManager/ProgramSettings.cc]: I think the only way to make this consistent is to move it to a separate input argument `debug_protocol_messages` or something like that, and have that displayed using `spdlog::debug` with an additional prefix `[protocol]`

Comment (veggiesaurus) [reply src/SessionManager/ProgramSettings.cc]: That would leave us with something like 
`[2021-02-25 11:04:26.647] [debug] [protocol] <== REGISTER_VIEWER`

Comment (confluence) [reply src/SessionManager/ProgramSettings.cc]: I think that we should use separate flags for protocol messages *and* performance messages, and log performance messages to `info`, instead of using the `trace` level for them.

So

* `log_performance` -> performance logged to `info` with added `[performance]` prefix
* `log_protocol_messages` -> ICD messages logged to `debug` with added `[protocol]` prefix
* remove `trace` / `performance` level completely

File: src/Logger/Logger.cc [hunk 8]
```diff
@@ -78,3 +84,25 @@ void InitLogger(bool no_log_file, int verbosity) {
...
+
+void LogReceivedEventType(const CARTA::EventType& event_type) {
+    auto event_name = CARTA::EventType_Name(CARTA::EventType(event_type));
+    if (!event_name.empty()) {
+        if (log_icd_messages) {
+            spdlog::debug("<== {}", event_name);
+        }
+    } else {
+        spdlog::error("Unknown event type: {}!", event_type);
+    }
```
Comment (confluence) [inline src/Logger/Logger.cc]: Please disregard my previous remark about logging this even when we aren't logging ICD messages -- we already log an error for an unrecognised received message in `OnMessageTask`. And I don't think it makes sense to check for unrecognised outgoing messages. So we can put the `log_icd_messages` check at the top level, and also log these unknown event type messages to `debug` like the other protocol messages.

**Review by confluence — CHANGES_REQUESTED** [review]

File: src/SessionManager/ProgramSettings.cc (hunk 7 above)
Comment (veggiesaurus) [reply src/SessionManager/ProgramSettings.cc]: I'm happy with that suggestion. However, I do think elegantly adding a `[performance]` prefix might be a little tricky, since we need to handle variadic arguments. 

@markccchiang please give this a try

File: src/Logger/Logger.cc [hunk 9]
```diff
@@ -50,31 +103,46 @@ void InitLogger(bool no_log_file, int verbosity) {
...
-    // Set flush policy on severity
-    stdout_logger->flush_on(spdlog::level::err);
-
-    // Register the stdout logger
-    if (!spdlog::get(STDOUT_TAG)) {
-        spdlog::register_logger(stdout_logger);
+void LogReceivedEventType(const CARTA::EventType& event_type) {
+    auto event_name = CARTA::EventType_Name(CARTA::EventType(event_type));
+    if (!event_name.empty()) {
+        if (log_protocol_messages) {
```
Comment (confluence) [inline src/Logger/Logger.cc]: Please put this check on the top level, and don't log anything if `log_protocol_messages` is unset.

File: src/Logger/Logger.cc [hunk 10]
```diff
@@ -50,31 +103,46 @@ void InitLogger(bool no_log_file, int verbosity) {
...
+            spdlog::debug("[protocol] <== {}", event_name);
+        }
     } else {
-        spdlog::critical("Duplicate registration of the logger: {}!", STDOUT_TAG);
+        spdlog::debug("Unknown event type: {}!", event_type);
```
Comment (confluence) [inline src/Logger/Logger.cc]: Please make this message format match the known event protocol message -- maybe something like `"[protocol] <== unknown event type: {}!"`

File: src/Logger/Logger.cc [hunk 11]
```diff
@@ -50,31 +103,46 @@ void InitLogger(bool no_log_file, int verbosity) {
...
-    if (!no_log_file) {
-        spdlog::info("Writing to the log file: {}", log_fullname);
+void LogSentEventType(const CARTA::EventType& event_type) {
+    auto event_name = CARTA::EventType_Name(CARTA::EventType(event_type));
+    if (!event_name.empty()) {
+        if (log_protocol_messages) {
+            spdlog::debug("[protocol] ==> {}", event_name);
+        }
+    } else {
+        spdlog::debug("Unknown event type: {}!", event_type);
```
Comment (confluence) [inline src/Logger/Logger.cc]: As above.

File: src/Logger/Logger.cc [hunk 12]
```diff
@@ -50,31 +103,46 @@ void InitLogger(bool no_log_file, int verbosity) {
             stdout_logger->set_level(spdlog::level::warn);
             break;
         case 5:
```
Comment (confluence) [inline src/Logger/Logger.cc]: Has 4 (info) disappeared?

In the discussion above we realised that the cleanest way to do this is with separate flags both for performance and for protocol logging (please see my comments below).

File: src/SessionManager/ProgramSettings.cc [hunk 13]
```diff
@@ -75,8 +75,9 @@ ProgramSettings::ProgramSettings(int argc, char** argv) {
  2   error
  3   warning
  4   info
- 5   debug
- 6   trace)");
+ 5   info + performance messages
+ 6   debug
+ 7   debug + protocol messages)");
```
Comment (confluence) [inline src/SessionManager/ProgramSettings.cc]: We should restore this to just `5 debug`, and use explicit optional flags called `log-performance` and `log-protocol-messages` to turn these options on.

If you add the flags, I will update the help messages.

**Review by confluence — CHANGES_REQUESTED** [review]
I think this is almost done, but we decided that the approach of a single log level number wasn't working for the performance and protocol messages -- there should be optional boolean flags for both of these.

File: src/SessionManager/ProgramSettings.cc (hunk 13 above)
Comment (markccchiang) [reply src/SessionManager/ProgramSettings.cc]: So there are `6` verbosity levels, and we add `--log-performance` and `--log-protocol-messages` options?

Comment (veggiesaurus) [reply src/SessionManager/ProgramSettings.cc]: Yes, that should work. Although we should be consistent with our use of _ in our arguments

Comment (confluence) [reply src/SessionManager/ProgramSettings.cc]: Yes, that's right. But only 5 verbosity levels (excluding `off`) -- we currently aren't actually using `trace` for anything, so we should remove it completely.

Comment (confluence) [reply src/SessionManager/ProgramSettings.cc]: My bad -- as @veggiesaurus points out, we use underscores in our option names, so we should use `log_performance` and `log_protocol_messages`.

Comment (markccchiang) [reply src/SessionManager/ProgramSettings.cc]: OK. Will do it later.

File: src/Logger/Logger.cc [hunk 14]
```diff
@@ -14,7 +14,11 @@ namespace fs = boost::filesystem;
 namespace fs = std::filesystem;
 #endif
 
-void InitLogger(bool no_log_file, int verbosity) {
+static bool log_protocol_messages(false);
+
+void InitLogger(bool no_log_file, int verbosity, bool log_performance, bool log_protocol_messages_) {
+    log_protocol_messages = log_protocol_messages_;
```
Comment (confluence) [inline src/Logger/Logger.cc:20]: Can we use `this` here to avoid using a different parameter name?

File: src/Logger/Logger.cc [hunk 15]
```diff
@@ -35,11 +39,11 @@ void InitLogger(bool no_log_file, int verbosity) {
...
     auto stdout_logger = std::make_shared<spdlog::logger>(STDOUT_TAG, std::begin(stdout_sinks), std::end(stdout_sinks));
 
+    // Set flush policy on severity
+    stdout_logger->flush_on(spdlog::level::err);
+
     // Set logger's level according to the verbosity number
     switch (verbosity) {
-        case 0:
-            stdout_logger->set_level(spdlog::level::off);
-            break;
```
Comment (confluence) [inline src/Logger/Logger.cc]: This should still be an option -- please put it back.

File: src/SessionManager/ProgramSettings.cc [hunk 16]
```diff
@@ -70,13 +72,11 @@ ProgramSettings::ProgramSettings(int argc, char** argv) {
     auto result = options.parse(argc, argv);
 
     std::string log_levels(R"(
- 0   off
```
Comment (confluence) [inline src/SessionManager/ProgramSettings.cc]: See previous comment; please put this back.

File: src/Logger/Logger.cc [hunk 17]
```diff
@@ -49,32 +53,78 @@ void InitLogger(bool no_log_file, int verbosity) {
...
             stdout_logger->set_level(spdlog::level::debug);
             break;
-        case 6:
-            stdout_logger->set_level(spdlog::level::trace);
-            break;
         default: {
             stdout_logger->set_level(spdlog::level::info);
             break;
         }
     }
```
Comment (confluence) [inline src/Logger/Logger.cc:70]: Please also set the level of the performance logger to the same level as the default logger.

At the moment there is an inconsistency between the two flags: if log_protocol_messages is enabled, but the log level is < debug, no protocol messages are printed -- which is the behaviour I would expect, because the protocol messages are logged at the debug level. But because the performance messages are implemented as a separate logger, if log_performance is enabled they are always logged, even if the log level is < info, even though they are now info level messages. We should set the perf logger level to the same level, so that the verbosity flag always takes precedence.

**Review by confluence — CHANGES_REQUESTED** [review]
This is good -- but the missing "off" level needs to come back, and the perf log level should match the default log level.

I have noticed that some casacore messages are printed even when our logs are silenced -- I will see if I can track these down. I'm not sure if we can suppress them easily; it would be nice, but it's not necessary for this PR.

File: src/Logger/Logger.cc [hunk 18]
```diff
@@ -14,7 +14,11 @@ namespace fs = boost::filesystem;
 namespace fs = std::filesystem;
 #endif
 
-void InitLogger(bool no_log_file, int verbosity) {
+static bool log_protocol_messages(false);
+
+void InitLogger(bool no_log_file, int verbosity, bool log_performance, bool this_log_protocol_messages) {
+    log_protocol_messages = this_log_protocol_messages;
```
Comment (confluence) [inline src/Logger/Logger.cc]: ~I meant that you could use the `this` pointer to refer to the member variable, and call the parameter the same thing.~

File: src/Logger/Logger.cc [hunk 19]
```diff
@@ -49,32 +56,104 @@ void InitLogger(bool no_log_file, int verbosity) {
...
+                perf_logger->set_level(spdlog::level::info);
+                break;
+            case 5:
+                perf_logger->set_level(spdlog::level::debug);
+                break;
+            default: {
+                perf_logger->set_level(spdlog::level::info);
+                break;
+            }
+        }
```
Comment (confluence) [inline src/Logger/Logger.cc]: Instead of replicating this, read the level from the default logger.

**Review by confluence — CHANGES_REQUESTED** [review]

File: src/Logger/Logger.cc (hunk 18 above)
Comment (markccchiang) [reply src/Logger/Logger.cc]: But this syntax would result in a compile error. Or just create a Logger class?

Comment (confluence) [reply src/Logger/Logger.cc]: Sorry; I didn't notice that the function is not a class member. The solution you had before (with the underscore at the end) was fine!

**Review by confluence — CHANGES_REQUESTED** [review]

**Review by confluence — APPROVED** [review]
I have updated the help descriptions for the new flags. Everything now seems to be working as expected.

@veggiesaurus and @kswang1029 , are we *sure* that we want the performance messages to be logged at the `info` level? They're verbose enough that `debug` may be more appropriate. This would be a very small change.

**Comment by kswang1029** [comment]
> I have updated the help descriptions for the new flags. Everything now seems to be working as expected.
> 
> @veggiesaurus and @kswang1029 , are we _sure_ that we want the performance messages to be logged at the `info` level? They're verbose enough that `debug` may be more appropriate. This would be a very small change.

debug sounds proper.
